language: rust

rust:
  - stable

script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/target/release/mm_publish
    - $TRAVIS_BUILD_DIR/target/release/mm_subscribe
  skip_cleanup: true
  on:
    tags: true

cache: cargo
